baseURL = 'https://about.neodb.social/'
locale = 'zh-cn'
title = 'NeoDB 中文指南'
theme = "PaperMod"
ignoreLogs = ['warning-partial-superfluous-prefix']

[params]
ShowToc = true
TocOpen = true
ShowShareButtons = false
author = "NeoDB"
editPost.URL = 'https://github.com/neodb-social/about.neodb.social/blob/main/content'
editPost.Text = '为本文提供修改建议'
editPost.appendFilePath = true
homeInfoParams.Title = "NeoDB 中文指南"
homeInfoParams.Content = "从注册、搜索、标记、导入数据到联邦社交，帮助中文用户开始使用 neodb.social。"
socialIcons = [
    { name = "github", url = "https://github.com/neodb-social" },
    { name = "discord", url = "https://discord.gg/8KweCuApaK" },
    { name = "mastodon", url = "https://mastodon.social/@neodb" },
    { name = "bluesky", url = "https://bsky.app/profile/did:plc:ui2d3qu2ltydsyskmnuvi4ay" },
    { name = "twitter", url = "https://twitter.com/NeoDBsocial" },
]
